### ISSUE TITLE
sometime map not loading 

### ISSUE THREAD

**Issue by tealtoxic** [thebrightspark/AsyncLocator#9]
hai! do you know why this happens? 1.18.2 version.
![javaw_1CIngDgCWg](https://github.com/thebrightspark/AsyncLocator/assets/21116787/0e54b949-2806-4e4f-b36b-b8f4536679c8)

map with chest load very fast btw. only sometime the map is like in the picture.

**Comment by tealtoxic** [comment]
after flying around lootboxes to check on maps, so far only 1 map not loading which is the one near spawn.. i guess it needs more time to generate.

**Comment by thebrightspark** [comment]
So long as you leave it in the chest, it should finish locating. The amount of time it takes purely depends on the structure's spawning requirements. Something like a Buried Treasure Map is one of the worst, because it has to check *every chunk* around.

There are edge cases, like https://github.com/thebrightspark/AsyncLocator/issues/8 where it won't work if you break the chest, but I will fix that. But bear in mind I don't intend to down-port features to older versions like 1.18.2.

**Comment by tealtoxic** [comment]
roger that. thank you!
